-- ================================================
-- FASCIOLI — Importacion de datos reales de Ascensores
-- Generado a partir de 'contratos ascensores y rampas 2026.xlsx'
-- Idempotente: se puede correr mas de una vez sin duplicar datos
-- Requiere haber corrido antes schema_contratos.sql y schema_contratos_v2.sql
-- ================================================

-- 1) Edificios: crea los que todavia no existan en mant_clientes (por nombre)
insert into mant_clientes (nombre) select 'Avenida Italia 7191' where not exists (select 1 from mant_clientes where nombre = 'Avenida Italia 7191');
insert into mant_clientes (nombre) select 'Deja Vu' where not exists (select 1 from mant_clientes where nombre = 'Deja Vu');
insert into mant_clientes (nombre) select 'Retamosa' where not exists (select 1 from mant_clientes where nombre = 'Retamosa');
insert into mant_clientes (nombre) select 'Castelvetrano I' where not exists (select 1 from mant_clientes where nombre = 'Castelvetrano I');
insert into mant_clientes (nombre) select 'Avenida Italia 3117' where not exists (select 1 from mant_clientes where nombre = 'Avenida Italia 3117');
insert into mant_clientes (nombre) select 'Missouri' where not exists (select 1 from mant_clientes where nombre = 'Missouri');
insert into mant_clientes (nombre) select 'Orinoco' where not exists (select 1 from mant_clientes where nombre = 'Orinoco');
insert into mant_clientes (nombre) select 'Minas' where not exists (select 1 from mant_clientes where nombre = 'Minas');
insert into mant_clientes (nombre) select 'Velsen 4575' where not exists (select 1 from mant_clientes where nombre = 'Velsen 4575');
insert into mant_clientes (nombre) select 'Sirius' where not exists (select 1 from mant_clientes where nombre = 'Sirius');
insert into mant_clientes (nombre) select 'Nasadrano' where not exists (select 1 from mant_clientes where nombre = 'Nasadrano');
insert into mant_clientes (nombre) select '18 de Diciembre 1511' where not exists (select 1 from mant_clientes where nombre = '18 de Diciembre 1511');
insert into mant_clientes (nombre) select 'Ibia I' where not exists (select 1 from mant_clientes where nombre = 'Ibia I');
insert into mant_clientes (nombre) select 'La Paz' where not exists (select 1 from mant_clientes where nombre = 'La Paz');
insert into mant_clientes (nombre) select 'Mones Roses' where not exists (select 1 from mant_clientes where nombre = 'Mones Roses');
insert into mant_clientes (nombre) select 'Cap Camarat' where not exists (select 1 from mant_clientes where nombre = 'Cap Camarat');
insert into mant_clientes (nombre) select 'Le mans' where not exists (select 1 from mant_clientes where nombre = 'Le mans');
insert into mant_clientes (nombre) select 'Tella' where not exists (select 1 from mant_clientes where nombre = 'Tella');
insert into mant_clientes (nombre) select 'Orion' where not exists (select 1 from mant_clientes where nombre = 'Orion');
insert into mant_clientes (nombre) select 'Adomar' where not exists (select 1 from mant_clientes where nombre = 'Adomar');
insert into mant_clientes (nombre) select 'Ñande Roga' where not exists (select 1 from mant_clientes where nombre = 'Ñande Roga');
insert into mant_clientes (nombre) select 'Shungo' where not exists (select 1 from mant_clientes where nombre = 'Shungo');
insert into mant_clientes (nombre) select 'Litore' where not exists (select 1 from mant_clientes where nombre = 'Litore');
insert into mant_clientes (nombre) select 'Plaza Fabini' where not exists (select 1 from mant_clientes where nombre = 'Plaza Fabini');
insert into mant_clientes (nombre) select 'Rossel y Rius' where not exists (select 1 from mant_clientes where nombre = 'Rossel y Rius');
insert into mant_clientes (nombre) select 'Cooper y Fedra' where not exists (select 1 from mant_clientes where nombre = 'Cooper y Fedra');
insert into mant_clientes (nombre) select 'Bel Air' where not exists (select 1 from mant_clientes where nombre = 'Bel Air');
insert into mant_clientes (nombre) select 'Aconcagua' where not exists (select 1 from mant_clientes where nombre = 'Aconcagua');
insert into mant_clientes (nombre) select 'Aleti de Bilbao' where not exists (select 1 from mant_clientes where nombre = 'Aleti de Bilbao');
insert into mant_clientes (nombre) select 'Maximo Tajes' where not exists (select 1 from mant_clientes where nombre = 'Maximo Tajes');
insert into mant_clientes (nombre) select 'Michigan I' where not exists (select 1 from mant_clientes where nombre = 'Michigan I');
insert into mant_clientes (nombre) select 'Patria Rene 1696' where not exists (select 1 from mant_clientes where nombre = 'Patria Rene 1696');
insert into mant_clientes (nombre) select 'Requena' where not exists (select 1 from mant_clientes where nombre = 'Requena');
insert into mant_clientes (nombre) select 'Garrido' where not exists (select 1 from mant_clientes where nombre = 'Garrido');
insert into mant_clientes (nombre) select 'Hipolito Yrigoyen 1514' where not exists (select 1 from mant_clientes where nombre = 'Hipolito Yrigoyen 1514');
insert into mant_clientes (nombre) select 'De los pocitos' where not exists (select 1 from mant_clientes where nombre = 'De los pocitos');
insert into mant_clientes (nombre) select 'Pilares del Centro' where not exists (select 1 from mant_clientes where nombre = 'Pilares del Centro');
insert into mant_clientes (nombre) select 'Punta Brava' where not exists (select 1 from mant_clientes where nombre = 'Punta Brava');
insert into mant_clientes (nombre) select 'Sea Park' where not exists (select 1 from mant_clientes where nombre = 'Sea Park');
insert into mant_clientes (nombre) select 'Terrazas del Molino' where not exists (select 1 from mant_clientes where nombre = 'Terrazas del Molino');
insert into mant_clientes (nombre) select 'Solano Garcia 2631' where not exists (select 1 from mant_clientes where nombre = 'Solano Garcia 2631');
insert into mant_clientes (nombre) select 'Solar de Verdi' where not exists (select 1 from mant_clientes where nombre = 'Solar de Verdi');
insert into mant_clientes (nombre) select 'Margus' where not exists (select 1 from mant_clientes where nombre = 'Margus');
insert into mant_clientes (nombre) select 'Citadino Prado' where not exists (select 1 from mant_clientes where nombre = 'Citadino Prado');
insert into mant_clientes (nombre) select 'La Riviera' where not exists (select 1 from mant_clientes where nombre = 'La Riviera');
insert into mant_clientes (nombre) select 'Ensenada' where not exists (select 1 from mant_clientes where nombre = 'Ensenada');
insert into mant_clientes (nombre) select 'Requena I' where not exists (select 1 from mant_clientes where nombre = 'Requena I');
insert into mant_clientes (nombre) select 'Acegua' where not exists (select 1 from mant_clientes where nombre = 'Acegua');
insert into mant_clientes (nombre) select 'Ciudad de Paris' where not exists (select 1 from mant_clientes where nombre = 'Ciudad de Paris');
insert into mant_clientes (nombre) select 'Residencial Propios' where not exists (select 1 from mant_clientes where nombre = 'Residencial Propios');
insert into mant_clientes (nombre) select 'Del Repecho' where not exists (select 1 from mant_clientes where nombre = 'Del Repecho');
insert into mant_clientes (nombre) select 'Verdi 4272' where not exists (select 1 from mant_clientes where nombre = 'Verdi 4272');
insert into mant_clientes (nombre) select 'Patria Rene 1652-1660' where not exists (select 1 from mant_clientes where nombre = 'Patria Rene 1652-1660');
insert into mant_clientes (nombre) select 'Gallinal 1642' where not exists (select 1 from mant_clientes where nombre = 'Gallinal 1642');
insert into mant_clientes (nombre) select 'Terrazas de Propios' where not exists (select 1 from mant_clientes where nombre = 'Terrazas de Propios');
insert into mant_clientes (nombre) select 'Colombes III' where not exists (select 1 from mant_clientes where nombre = 'Colombes III');
insert into mant_clientes (nombre) select 'Rio Negro' where not exists (select 1 from mant_clientes where nombre = 'Rio Negro');
insert into mant_clientes (nombre) select 'Tampico' where not exists (select 1 from mant_clientes where nombre = 'Tampico');
insert into mant_clientes (nombre) select 'Playa Oriente II' where not exists (select 1 from mant_clientes where nombre = 'Playa Oriente II');
insert into mant_clientes (nombre) select 'Isla de las Gaviotas' where not exists (select 1 from mant_clientes where nombre = 'Isla de las Gaviotas');
insert into mant_clientes (nombre) select 'Provi I' where not exists (select 1 from mant_clientes where nombre = 'Provi I');
insert into mant_clientes (nombre) select 'Quadra' where not exists (select 1 from mant_clientes where nombre = 'Quadra');
insert into mant_clientes (nombre) select 'Ramver' where not exists (select 1 from mant_clientes where nombre = 'Ramver');
insert into mant_clientes (nombre) select 'Portonovo' where not exists (select 1 from mant_clientes where nombre = 'Portonovo');
insert into mant_clientes (nombre) select '720' where not exists (select 1 from mant_clientes where nombre = '720');
insert into mant_clientes (nombre) select 'Las Palmas' where not exists (select 1 from mant_clientes where nombre = 'Las Palmas');
insert into mant_clientes (nombre) select 'Millan' where not exists (select 1 from mant_clientes where nombre = 'Millan');
insert into mant_clientes (nombre) select 'Cooperativa 19 de Junio' where not exists (select 1 from mant_clientes where nombre = 'Cooperativa 19 de Junio');
insert into mant_clientes (nombre) select 'Parque Shopping' where not exists (select 1 from mant_clientes where nombre = 'Parque Shopping');
insert into mant_clientes (nombre) select 'Tiffany II' where not exists (select 1 from mant_clientes where nombre = 'Tiffany II');
insert into mant_clientes (nombre) select 'Colombes II' where not exists (select 1 from mant_clientes where nombre = 'Colombes II');
insert into mant_clientes (nombre) select 'Echevarriarza' where not exists (select 1 from mant_clientes where nombre = 'Echevarriarza');
insert into mant_clientes (nombre) select 'El Ombu' where not exists (select 1 from mant_clientes where nombre = 'El Ombu');
insert into mant_clientes (nombre) select 'Ria de Betanzos' where not exists (select 1 from mant_clientes where nombre = 'Ria de Betanzos');
insert into mant_clientes (nombre) select 'Rocamar' where not exists (select 1 from mant_clientes where nombre = 'Rocamar');
insert into mant_clientes (nombre) select 'Lomas del Mar' where not exists (select 1 from mant_clientes where nombre = 'Lomas del Mar');
insert into mant_clientes (nombre) select 'Cooperativa Jose Pedro Varela' where not exists (select 1 from mant_clientes where nombre = 'Cooperativa Jose Pedro Varela');
insert into mant_clientes (nombre) select 'Malena' where not exists (select 1 from mant_clientes where nombre = 'Malena');
insert into mant_clientes (nombre) select 'Los Cedros' where not exists (select 1 from mant_clientes where nombre = 'Los Cedros');
insert into mant_clientes (nombre) select 'Ambrosio Velazco' where not exists (select 1 from mant_clientes where nombre = 'Ambrosio Velazco');
insert into mant_clientes (nombre) select 'Fidias II' where not exists (select 1 from mant_clientes where nombre = 'Fidias II');
insert into mant_clientes (nombre) select 'Asamblea' where not exists (select 1 from mant_clientes where nombre = 'Asamblea');
insert into mant_clientes (nombre) select 'Miravalles' where not exists (select 1 from mant_clientes where nombre = 'Miravalles');
insert into mant_clientes (nombre) select 'Los Fontanes' where not exists (select 1 from mant_clientes where nombre = 'Los Fontanes');
insert into mant_clientes (nombre) select 'Belgrano I' where not exists (select 1 from mant_clientes where nombre = 'Belgrano I');
insert into mant_clientes (nombre) select 'Kalimera' where not exists (select 1 from mant_clientes where nombre = 'Kalimera');
insert into mant_clientes (nombre) select 'Taboba' where not exists (select 1 from mant_clientes where nombre = 'Taboba');
insert into mant_clientes (nombre) select 'Enrique I' where not exists (select 1 from mant_clientes where nombre = 'Enrique I');
insert into mant_clientes (nombre) select 'Country del Molino' where not exists (select 1 from mant_clientes where nombre = 'Country del Molino');
insert into mant_clientes (nombre) select 'Pireo II' where not exists (select 1 from mant_clientes where nombre = 'Pireo II');
insert into mant_clientes (nombre) select 'Terrazas de Legrand' where not exists (select 1 from mant_clientes where nombre = 'Terrazas de Legrand');
insert into mant_clientes (nombre) select 'Rostand Place' where not exists (select 1 from mant_clientes where nombre = 'Rostand Place');
insert into mant_clientes (nombre) select 'Mauritalia II' where not exists (select 1 from mant_clientes where nombre = 'Mauritalia II');
insert into mant_clientes (nombre) select 'Tiber' where not exists (select 1 from mant_clientes where nombre = 'Tiber');
insert into mant_clientes (nombre) select 'Riviera' where not exists (select 1 from mant_clientes where nombre = 'Riviera');
insert into mant_clientes (nombre) select 'Castro Quintela' where not exists (select 1 from mant_clientes where nombre = 'Castro Quintela');
insert into mant_clientes (nombre) select 'Merides' where not exists (select 1 from mant_clientes where nombre = 'Merides');
insert into mant_clientes (nombre) select 'Gallinal 1384' where not exists (select 1 from mant_clientes where nombre = 'Gallinal 1384');
insert into mant_clientes (nombre) select 'Altea' where not exists (select 1 from mant_clientes where nombre = 'Altea');
insert into mant_clientes (nombre) select 'Santiago de Anca' where not exists (select 1 from mant_clientes where nombre = 'Santiago de Anca');
insert into mant_clientes (nombre) select 'Buganvilias' where not exists (select 1 from mant_clientes where nombre = 'Buganvilias');
insert into mant_clientes (nombre) select 'Monteforte II' where not exists (select 1 from mant_clientes where nombre = 'Monteforte II');
insert into mant_clientes (nombre) select 'Cooperativa Coviba' where not exists (select 1 from mant_clientes where nombre = 'Cooperativa Coviba');
insert into mant_clientes (nombre) select 'Residencial Artigas' where not exists (select 1 from mant_clientes where nombre = 'Residencial Artigas');
insert into mant_clientes (nombre) select 'Green Design' where not exists (select 1 from mant_clientes where nombre = 'Green Design');
insert into mant_clientes (nombre) select 'Siracusa Park' where not exists (select 1 from mant_clientes where nombre = 'Siracusa Park');
insert into mant_clientes (nombre) select 'Remo' where not exists (select 1 from mant_clientes where nombre = 'Remo');
insert into mant_clientes (nombre) select 'Playa Honda II' where not exists (select 1 from mant_clientes where nombre = 'Playa Honda II');
insert into mant_clientes (nombre) select 'Cooperativa Copina' where not exists (select 1 from mant_clientes where nombre = 'Cooperativa Copina');
insert into mant_clientes (nombre) select 'Beiramar' where not exists (select 1 from mant_clientes where nombre = 'Beiramar');
insert into mant_clientes (nombre) select 'Cagancha' where not exists (select 1 from mant_clientes where nombre = 'Cagancha');
insert into mant_clientes (nombre) select 'Arizona' where not exists (select 1 from mant_clientes where nombre = 'Arizona');
insert into mant_clientes (nombre) select 'Giulianova' where not exists (select 1 from mant_clientes where nombre = 'Giulianova');
insert into mant_clientes (nombre) select 'Pilcomayo' where not exists (select 1 from mant_clientes where nombre = 'Pilcomayo');
insert into mant_clientes (nombre) select 'Agraciada I' where not exists (select 1 from mant_clientes where nombre = 'Agraciada I');
insert into mant_clientes (nombre) select 'San Luis' where not exists (select 1 from mant_clientes where nombre = 'San Luis');
insert into mant_clientes (nombre) select 'Vera' where not exists (select 1 from mant_clientes where nombre = 'Vera');
insert into mant_clientes (nombre) select 'Porongos' where not exists (select 1 from mant_clientes where nombre = 'Porongos');
insert into mant_clientes (nombre) select 'Almería' where not exists (select 1 from mant_clientes where nombre = 'Almería');
insert into mant_clientes (nombre) select 'Gaboto 1814' where not exists (select 1 from mant_clientes where nombre = 'Gaboto 1814');
insert into mant_clientes (nombre) select 'Altos del Molino' where not exists (select 1 from mant_clientes where nombre = 'Altos del Molino');
insert into mant_clientes (nombre) select 'Tulipan I' where not exists (select 1 from mant_clientes where nombre = 'Tulipan I');
insert into mant_clientes (nombre) select 'Rivera y Rimac' where not exists (select 1 from mant_clientes where nombre = 'Rivera y Rimac');
insert into mant_clientes (nombre) select 'Almería 4567' where not exists (select 1 from mant_clientes where nombre = 'Almería 4567');
insert into mant_clientes (nombre) select 'Ischia II' where not exists (select 1 from mant_clientes where nombre = 'Ischia II');
insert into mant_clientes (nombre) select 'Cairoli' where not exists (select 1 from mant_clientes where nombre = 'Cairoli');
insert into mant_clientes (nombre) select 'Torre Granada' where not exists (select 1 from mant_clientes where nombre = 'Torre Granada');
insert into mant_clientes (nombre) select 'Capri' where not exists (select 1 from mant_clientes where nombre = 'Capri');
insert into mant_clientes (nombre) select 'Candieira' where not exists (select 1 from mant_clientes where nombre = 'Candieira');
insert into mant_clientes (nombre) select 'La Defense' where not exists (select 1 from mant_clientes where nombre = 'La Defense');
insert into mant_clientes (nombre) select 'Oikos' where not exists (select 1 from mant_clientes where nombre = 'Oikos');
insert into mant_clientes (nombre) select 'Pagola' where not exists (select 1 from mant_clientes where nombre = 'Pagola');
insert into mant_clientes (nombre) select 'El Ceibo' where not exists (select 1 from mant_clientes where nombre = 'El Ceibo');
insert into mant_clientes (nombre) select 'Velsen 4441' where not exists (select 1 from mant_clientes where nombre = 'Velsen 4441');
insert into mant_clientes (nombre) select 'Tristan Narvaja' where not exists (select 1 from mant_clientes where nombre = 'Tristan Narvaja');
insert into mant_clientes (nombre) select 'Puertito I' where not exists (select 1 from mant_clientes where nombre = 'Puertito I');
insert into mant_clientes (nombre) select 'Barroso' where not exists (select 1 from mant_clientes where nombre = 'Barroso');
insert into mant_clientes (nombre) select 'Cooperativa Covideo' where not exists (select 1 from mant_clientes where nombre = 'Cooperativa Covideo');
insert into mant_clientes (nombre) select 'Abayubá' where not exists (select 1 from mant_clientes where nombre = 'Abayubá');
insert into mant_clientes (nombre) select 'Ayuí' where not exists (select 1 from mant_clientes where nombre = 'Ayuí');
insert into mant_clientes (nombre) select 'Fleming' where not exists (select 1 from mant_clientes where nombre = 'Fleming');
insert into mant_clientes (nombre) select 'La Palmera' where not exists (select 1 from mant_clientes where nombre = 'La Palmera');
insert into mant_clientes (nombre) select 'Sorrento' where not exists (select 1 from mant_clientes where nombre = 'Sorrento');
insert into mant_clientes (nombre) select 'Paysandú' where not exists (select 1 from mant_clientes where nombre = 'Paysandú');
insert into mant_clientes (nombre) select 'Kimberly' where not exists (select 1 from mant_clientes where nombre = 'Kimberly');
insert into mant_clientes (nombre) select 'Zonis' where not exists (select 1 from mant_clientes where nombre = 'Zonis');
insert into mant_clientes (nombre) select 'San Andres' where not exists (select 1 from mant_clientes where nombre = 'San Andres');
insert into mant_clientes (nombre) select 'Araguaney' where not exists (select 1 from mant_clientes where nombre = 'Araguaney');
insert into mant_clientes (nombre) select 'Bruno Mendez' where not exists (select 1 from mant_clientes where nombre = 'Bruno Mendez');
insert into mant_clientes (nombre) select 'Marly' where not exists (select 1 from mant_clientes where nombre = 'Marly');
insert into mant_clientes (nombre) select 'Bernardina' where not exists (select 1 from mant_clientes where nombre = 'Bernardina');
insert into mant_clientes (nombre) select 'Kentavros' where not exists (select 1 from mant_clientes where nombre = 'Kentavros');
insert into mant_clientes (nombre) select 'Green Village Park' where not exists (select 1 from mant_clientes where nombre = 'Green Village Park');
insert into mant_clientes (nombre) select 'Paraguay' where not exists (select 1 from mant_clientes where nombre = 'Paraguay');
insert into mant_clientes (nombre) select 'Ventura Design' where not exists (select 1 from mant_clientes where nombre = 'Ventura Design');
insert into mant_clientes (nombre) select 'Citadino Plaza Seregni' where not exists (select 1 from mant_clientes where nombre = 'Citadino Plaza Seregni');
insert into mant_clientes (nombre) select 'Marisdea' where not exists (select 1 from mant_clientes where nombre = 'Marisdea');
insert into mant_clientes (nombre) select 'Torre de Las Gaviotas' where not exists (select 1 from mant_clientes where nombre = 'Torre de Las Gaviotas');
insert into mant_clientes (nombre) select 'Tourmalet' where not exists (select 1 from mant_clientes where nombre = 'Tourmalet');
insert into mant_clientes (nombre) select 'Fenicio II' where not exists (select 1 from mant_clientes where nombre = 'Fenicio II');
insert into mant_clientes (nombre) select 'Sur' where not exists (select 1 from mant_clientes where nombre = 'Sur');
insert into mant_clientes (nombre) select 'Belgrano 2862' where not exists (select 1 from mant_clientes where nombre = 'Belgrano 2862');
insert into mant_clientes (nombre) select 'Anclamar' where not exists (select 1 from mant_clientes where nombre = 'Anclamar');
insert into mant_clientes (nombre) select 'Tenax' where not exists (select 1 from mant_clientes where nombre = 'Tenax');
insert into mant_clientes (nombre) select 'Resistencia' where not exists (select 1 from mant_clientes where nombre = 'Resistencia');
insert into mant_clientes (nombre) select 'Verdi 4399' where not exists (select 1 from mant_clientes where nombre = 'Verdi 4399');
insert into mant_clientes (nombre) select 'Nasazzi' where not exists (select 1 from mant_clientes where nombre = 'Nasazzi');
insert into mant_clientes (nombre) select 'Sepee' where not exists (select 1 from mant_clientes where nombre = 'Sepee');
insert into mant_clientes (nombre) select '6 de Octubre' where not exists (select 1 from mant_clientes where nombre = '6 de Octubre');
insert into mant_clientes (nombre) select 'Tao' where not exists (select 1 from mant_clientes where nombre = 'Tao');
insert into mant_clientes (nombre) select 'Capitan Tahití' where not exists (select 1 from mant_clientes where nombre = 'Capitan Tahití');
insert into mant_clientes (nombre) select 'Alamo' where not exists (select 1 from mant_clientes where nombre = 'Alamo');
insert into mant_clientes (nombre) select 'Marikar' where not exists (select 1 from mant_clientes where nombre = 'Marikar');
insert into mant_clientes (nombre) select 'Zone One' where not exists (select 1 from mant_clientes where nombre = 'Zone One');
insert into mant_clientes (nombre) select 'Patria Grito de Gloria 1683' where not exists (select 1 from mant_clientes where nombre = 'Patria Grito de Gloria 1683');
insert into mant_clientes (nombre) select 'Belgrano 2858 bis' where not exists (select 1 from mant_clientes where nombre = 'Belgrano 2858 bis');
insert into mant_clientes (nombre) select '29 de Abril' where not exists (select 1 from mant_clientes where nombre = '29 de Abril');
insert into mant_clientes (nombre) select 'Estivao' where not exists (select 1 from mant_clientes where nombre = 'Estivao');
insert into mant_clientes (nombre) select 'Novara Lofts' where not exists (select 1 from mant_clientes where nombre = 'Novara Lofts');
insert into mant_clientes (nombre) select 'Velzen' where not exists (select 1 from mant_clientes where nombre = 'Velzen');
insert into mant_clientes (nombre) select 'Oeste' where not exists (select 1 from mant_clientes where nombre = 'Oeste');
insert into mant_clientes (nombre) select 'Zorrilla de San Martín' where not exists (select 1 from mant_clientes where nombre = 'Zorrilla de San Martín');
insert into mant_clientes (nombre) select 'Amezaga' where not exists (select 1 from mant_clientes where nombre = 'Amezaga');
insert into mant_clientes (nombre) select 'Ramon Anador' where not exists (select 1 from mant_clientes where nombre = 'Ramon Anador');
insert into mant_clientes (nombre) select 'Azul de La Playa' where not exists (select 1 from mant_clientes where nombre = 'Azul de La Playa');
insert into mant_clientes (nombre) select 'Rivera 4575' where not exists (select 1 from mant_clientes where nombre = 'Rivera 4575');
insert into mant_clientes (nombre) select 'Hipolito Yrigoyen 1584' where not exists (select 1 from mant_clientes where nombre = 'Hipolito Yrigoyen 1584');
insert into mant_clientes (nombre) select 'Torres Parque Atahualpa' where not exists (select 1 from mant_clientes where nombre = 'Torres Parque Atahualpa');
insert into mant_clientes (nombre) select 'Il Duomo' where not exists (select 1 from mant_clientes where nombre = 'Il Duomo');
insert into mant_clientes (nombre) select 'Mood Plaza' where not exists (select 1 from mant_clientes where nombre = 'Mood Plaza');
insert into mant_clientes (nombre) select 'Avenida Italia 3133' where not exists (select 1 from mant_clientes where nombre = 'Avenida Italia 3133');
insert into mant_clientes (nombre) select 'Ibia III' where not exists (select 1 from mant_clientes where nombre = 'Ibia III');
insert into mant_clientes (nombre) select 'Andrea''s' where not exists (select 1 from mant_clientes where nombre = 'Andrea''s');
insert into mant_clientes (nombre) select 'Torre Marsala I' where not exists (select 1 from mant_clientes where nombre = 'Torre Marsala I');
insert into mant_clientes (nombre) select 'Durazno' where not exists (select 1 from mant_clientes where nombre = 'Durazno');
insert into mant_clientes (nombre) select 'Costa de Marfil' where not exists (select 1 from mant_clientes where nombre = 'Costa de Marfil');
insert into mant_clientes (nombre) select 'San Vicente' where not exists (select 1 from mant_clientes where nombre = 'San Vicente');
insert into mant_clientes (nombre) select 'Pereira' where not exists (select 1 from mant_clientes where nombre = 'Pereira');
insert into mant_clientes (nombre) select 'Canstatt' where not exists (select 1 from mant_clientes where nombre = 'Canstatt');
insert into mant_clientes (nombre) select 'Villa Ibirapita' where not exists (select 1 from mant_clientes where nombre = 'Villa Ibirapita');
insert into mant_clientes (nombre) select 'Azul' where not exists (select 1 from mant_clientes where nombre = 'Azul');
insert into mant_clientes (nombre) select 'Flavia' where not exists (select 1 from mant_clientes where nombre = 'Flavia');
insert into mant_clientes (nombre) select 'Mont Blanc' where not exists (select 1 from mant_clientes where nombre = 'Mont Blanc');
insert into mant_clientes (nombre) select 'Giardino Dei Fiumi' where not exists (select 1 from mant_clientes where nombre = 'Giardino Dei Fiumi');
insert into mant_clientes (nombre) select 'Asamblea 4371' where not exists (select 1 from mant_clientes where nombre = 'Asamblea 4371');
insert into mant_clientes (nombre) select 'Amatí' where not exists (select 1 from mant_clientes where nombre = 'Amatí');

-- 2) Catalogo de empresas de Ascensores
insert into contratos_empresas (nombre, categoria) values ('Adamoli', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Alfa', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Astor', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('C.E.A.H', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Caballeros', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Codau', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Coorporacion', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Cuma', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Curber', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Delta', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('FP', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Gerardo Laube', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Otecas', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Otis', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Sermas', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Sima', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Sur', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('TKE', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Tecnas', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Teknisur', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('VE', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Viñoles', 'ascensor') on conflict (nombre, categoria) do nothing;
insert into contratos_empresas (nombre, categoria) values ('Wagner', 'ascensor') on conflict (nombre, categoria) do nothing;

-- 3) Contratos de Ascensores (no se crea si el edificio ya tiene uno cargado)
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Mantenimiento', '2017-10-01', 5 from mant_clientes mc where mc.nombre = 'Deja Vu' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Mantenimiento', '2019-04-01', 3 from mant_clientes mc where mc.nombre = 'Retamosa' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Mantenimiento (Inicio el 01/04/2026)', '2030-03-31', 3 from mant_clientes mc where mc.nombre = 'Orinoco' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Wagner', 'Mantenimiento', '2011-09-01', 2 from mant_clientes mc where mc.nombre = 'Sirius' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Curber', 'Mantenimiento', '2025-09-01', 2 from mant_clientes mc where mc.nombre = 'Nasadrano' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Basico', '2020-11-01', 3 from mant_clientes mc where mc.nombre = 'La Paz' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2010-04-01', 3 from mant_clientes mc where mc.nombre = 'Cap Camarat' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Viñoles', 'Integral', '2003-10-01', 4 from mant_clientes mc where mc.nombre = 'Le mans' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Basico', '2014-02-01', 3 from mant_clientes mc where mc.nombre = 'Tella' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2019-09-01', 3 from mant_clientes mc where mc.nombre = 'Orion' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Teknisur', 'Integral', '2012-12-01', 1 from mant_clientes mc where mc.nombre = 'Adomar' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Tecnas', 'Basico', '2020-08-01', 1 from mant_clientes mc where mc.nombre = 'Ñande Roga' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2004-04-01', 2 from mant_clientes mc where mc.nombre = 'Shungo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Basico', '2024-04-01', 3 from mant_clientes mc where mc.nombre = 'Litore' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2003-05-01', 3 from mant_clientes mc where mc.nombre = 'Plaza Fabini' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sima', 'Integral', '2007-08-09', 1 from mant_clientes mc where mc.nombre = 'Bel Air' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '1997-06-01', 2 from mant_clientes mc where mc.nombre = 'Aconcagua' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2015-12-01', 3 from mant_clientes mc where mc.nombre = 'Aleti de Bilbao' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2016-08-01', 3 from mant_clientes mc where mc.nombre = 'Requena' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sermas', 'Integral', '2023-07-01', 2 from mant_clientes mc where mc.nombre = 'De los pocitos' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'C.E.A.H', 'Integral', '2025-12-01', 2 from mant_clientes mc where mc.nombre = 'Pilares del Centro' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Coorporacion', 'Integral', '2021-07-30', 2 from mant_clientes mc where mc.nombre = 'Punta Brava' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2017-05-01', 2 from mant_clientes mc where mc.nombre = 'Sea Park' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2003-10-01', 4 from mant_clientes mc where mc.nombre = 'Terrazas del Molino' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sur', null, '2019-10-24', 5 from mant_clientes mc where mc.nombre = 'Solar de Verdi' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2016-12-01', 2 from mant_clientes mc where mc.nombre = 'Citadino Prado' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Premium', '2024-02-01', 3 from mant_clientes mc where mc.nombre = 'La Riviera' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '1999-06-01', 5 from mant_clientes mc where mc.nombre = 'Ensenada' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sur', 'Integral', '2022-06-07', 5 from mant_clientes mc where mc.nombre = 'Requena I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'VE', null, '2020-01-27', 1 from mant_clientes mc where mc.nombre = 'Ciudad de Paris' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sermas', null, '1997-08-01', 2 from mant_clientes mc where mc.nombre = 'Residencial Propios' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2009-04-01', 5 from mant_clientes mc where mc.nombre = 'Del Repecho' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2015-12-01', 3 from mant_clientes mc where mc.nombre = 'Terrazas de Propios' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', null, '2006-02-01', 2 from mant_clientes mc where mc.nombre = 'Colombes III' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sermas', 'Integral', '1997-09-01', 2 from mant_clientes mc where mc.nombre = 'Tampico' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'C.E.A.H', 'Integral', '2024-01-01', 3 from mant_clientes mc where mc.nombre = 'Playa Oriente II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2003-11-01', 5 from mant_clientes mc where mc.nombre = 'Isla de las Gaviotas' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2006-11-01', 3 from mant_clientes mc where mc.nombre = 'Provi I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2016-07-01', 5 from mant_clientes mc where mc.nombre = 'Quadra' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Cuma', null, '2012-12-01', 5 from mant_clientes mc where mc.nombre = 'Ramver' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2011-02-01', 2 from mant_clientes mc where mc.nombre = 'Portonovo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2012-11-01', 5 from mant_clientes mc where mc.nombre = '720' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2001-03-01', 5 from mant_clientes mc where mc.nombre = 'Las Palmas' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Coorporacion', 'Integral', '2014-07-01', 2 from mant_clientes mc where mc.nombre = 'Cooperativa 19 de Junio' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2022-06-01', 3 from mant_clientes mc where mc.nombre = 'Parque Shopping' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2015-11-01', 3 from mant_clientes mc where mc.nombre = 'Tiffany II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2001-05-01', 2 from mant_clientes mc where mc.nombre = 'Colombes II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'TKE', null, '2020-12-01', 5 from mant_clientes mc where mc.nombre = 'Echevarriarza' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '1991-03-01', 3 from mant_clientes mc where mc.nombre = 'El Ombu' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2012-08-01', 2 from mant_clientes mc where mc.nombre = 'Ria de Betanzos' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2001-12-01', 5 from mant_clientes mc where mc.nombre = 'Rocamar' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2009-06-01', 3 from mant_clientes mc where mc.nombre = 'Lomas del Mar' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Caballeros', 'Integral', '2008-11-01', 5 from mant_clientes mc where mc.nombre = 'Cooperativa Jose Pedro Varela' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '1997-06-01', 2 from mant_clientes mc where mc.nombre = 'Malena' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2023-09-01', 4 from mant_clientes mc where mc.nombre = 'Los Cedros' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'C.E.A.H', 'Basico', '2022-04-01', 2 from mant_clientes mc where mc.nombre = 'Ambrosio Velazco' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2066-08-01', 3 from mant_clientes mc where mc.nombre = 'Fidias II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sima', 'Integral', '2004-04-01', 1 from mant_clientes mc where mc.nombre = 'Los Fontanes' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integreal', '2016-03-01', 2 from mant_clientes mc where mc.nombre = 'Belgrano I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2002-10-01', 5 from mant_clientes mc where mc.nombre = 'Kalimera' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral (Inicio en 2015)', '2015-07-01', 3 from mant_clientes mc where mc.nombre = 'Pireo II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'TKE', null, '2017-07-01', 3 from mant_clientes mc where mc.nombre = 'Terrazas de Legrand' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Caballeros', 'Integral', '2016-01-01', 5 from mant_clientes mc where mc.nombre = 'Mauritalia II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Teknisur', 'No tenemos contrato', null, null from mant_clientes mc where mc.nombre = 'Tiber' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2019-09-01', 3 from mant_clientes mc where mc.nombre = 'Merides' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2006-02-01', 2 from mant_clientes mc where mc.nombre = 'Gallinal 1384' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sima', null, '1992-09-28', 2 from mant_clientes mc where mc.nombre = 'Altea' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2016-04-01', 2 from mant_clientes mc where mc.nombre = 'Buganvilias' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2011-04-01', 2 from mant_clientes mc where mc.nombre = 'Monteforte II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sermas', 'Integral', '2004-04-01', 2 from mant_clientes mc where mc.nombre = 'Residencial Artigas' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'TKE', null, '2024-03-21', 1 from mant_clientes mc where mc.nombre = 'Green Design' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Coorporacion', 'Integral', '2011-07-01', 2 from mant_clientes mc where mc.nombre = 'Remo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sima', 'Basico', '2014-09-01', 1 from mant_clientes mc where mc.nombre = 'Playa Honda II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '1996-07-01', 2 from mant_clientes mc where mc.nombre = 'Cooperativa Copina' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2003-04-01', 2 from mant_clientes mc where mc.nombre = 'Beiramar' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2021-04-01', 5 from mant_clientes mc where mc.nombre = 'Arizona' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Gerardo Laube', null, '1977-06-30', 1 from mant_clientes mc where mc.nombre = 'Giulianova' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Codau', 'Basico', '2022-11-19', 2 from mant_clientes mc where mc.nombre = 'Agraciada I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '1996-01-01', 2 from mant_clientes mc where mc.nombre = 'Almería' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2010-12-01', 3 from mant_clientes mc where mc.nombre = 'Altos del Molino' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2002-05-01', 2 from mant_clientes mc where mc.nombre = 'Tulipan I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2001-01-01', 1 from mant_clientes mc where mc.nombre = 'Ischia II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Astor', 'Basico', '1996-01-01', 1 from mant_clientes mc where mc.nombre = 'Torre Granada' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2023-07-01', 3 from mant_clientes mc where mc.nombre = 'Capri' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Basico', '2022-06-01', 3 from mant_clientes mc where mc.nombre = 'La Defense' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2024-08-01', 5 from mant_clientes mc where mc.nombre = 'Oikos' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '1999-01-01', 2 from mant_clientes mc where mc.nombre = 'Pagola' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2007-05-01', 2 from mant_clientes mc where mc.nombre = 'El Ceibo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Tecnas', 'Basico', '2021-08-01', 2 from mant_clientes mc where mc.nombre = 'Tristan Narvaja' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2009-11-01', 5 from mant_clientes mc where mc.nombre = 'Puertito I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otecas', null, '2019-08-01', 3 from mant_clientes mc where mc.nombre = 'Cooperativa Covideo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2022-03-01', 3 from mant_clientes mc where mc.nombre = 'Abayubá' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2010-09-01', 2 from mant_clientes mc where mc.nombre = 'Ayuí' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2013-01-01', 5 from mant_clientes mc where mc.nombre = 'Fleming' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2022-10-01', 3 from mant_clientes mc where mc.nombre = 'Sorrento' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2013-08-01', 5 from mant_clientes mc where mc.nombre = 'Kimberly' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Teknisur', 'Integral', '2017-05-01', 2 from mant_clientes mc where mc.nombre = 'San Andres' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2024-10-01', 3 from mant_clientes mc where mc.nombre = 'Araguaney' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Viñoles', 'Integral', '2003-01-01', 3 from mant_clientes mc where mc.nombre = 'Marly' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2017-01-01', 3 from mant_clientes mc where mc.nombre = 'Bernardina' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'FP', null, '1995-12-01', 2 from mant_clientes mc where mc.nombre = 'Paraguay' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2018-05-01', 2 from mant_clientes mc where mc.nombre = 'Ventura Design' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2017-10-01', 2 from mant_clientes mc where mc.nombre = 'Citadino Plaza Seregni' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sur', 'Integral', '2020-08-28', 2 from mant_clientes mc where mc.nombre = 'Marisdea' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2003-06-01', 2 from mant_clientes mc where mc.nombre = 'Torre de Las Gaviotas' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Gerardo Laube', null, '1977-09-14', 1 from mant_clientes mc where mc.nombre = 'Tourmalet' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otecas', null, '2023-08-01', 3 from mant_clientes mc where mc.nombre = 'Fenicio II' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2025-09-01', 3 from mant_clientes mc where mc.nombre = 'Anclamar' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Tecnas', null, '1986-10-10', null from mant_clientes mc where mc.nombre = 'Tenax' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'TKE', 'Integral', '2006-09-01', 5 from mant_clientes mc where mc.nombre = 'Nasazzi' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Astor', 'Integral', '2021-09-01', 2 from mant_clientes mc where mc.nombre = 'Capitan Tahití' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sur', null, '2022-05-11', 10 from mant_clientes mc where mc.nombre = 'Alamo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2021-06-14', 5 from mant_clientes mc where mc.nombre = 'Zone One' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2011-10-01', 2 from mant_clientes mc where mc.nombre = '29 de Abril' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Basico', '2025-12-01', 3 from mant_clientes mc where mc.nombre = 'Velzen' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Codau', null, '2025-08-31', 2 from mant_clientes mc where mc.nombre = 'Oeste' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, null, null from mant_clientes mc where mc.nombre = 'Azul de La Playa' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', null, '2016-03-01', 3 from mant_clientes mc where mc.nombre = 'Torres Parque Atahualpa' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', null, '2004-12-01', 4 from mant_clientes mc where mc.nombre = 'Il Duomo' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2023-08-23', 2 from mant_clientes mc where mc.nombre = 'Mood Plaza' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2000-02-01', 1 from mant_clientes mc where mc.nombre = 'Ibia III' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '2025-09-01', 2 from mant_clientes mc where mc.nombre = 'Andrea''s' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', 'Integral', '1991-09-01', 2 from mant_clientes mc where mc.nombre = 'Torre Marsala I' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Sur', 'Integral', '2019-07-24', 2 from mant_clientes mc where mc.nombre = 'Costa de Marfil' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otecas', 'Integral', '2003-12-01', 2 from mant_clientes mc where mc.nombre = 'San Vicente' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Adamoli', 'Integral', '2013-05-01', 2 from mant_clientes mc where mc.nombre = 'Pereira' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Alfa', 'Integral', '2008-12-01', 2 from mant_clientes mc where mc.nombre = 'Azul' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Delta', null, '1994-07-01', 3 from mant_clientes mc where mc.nombre = 'Mont Blanc' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
insert into contratos (cliente_id, categoria, empresa, tipo_contrato, fecha_firma_inicio, vigencia_anios) select mc.id, 'ascensor', 'Otis', 'Integral', '2022-06-01', 5 from mant_clientes mc where mc.nombre = 'Giardino Dei Fiumi' and not exists (select 1 from contratos co where co.cliente_id = mc.id and co.categoria = 'ascensor');
